### ISSUE TITLE
Django 1.8+ support

### ISSUE THREAD

**Issue by jeacaveo** [dimagi/django-prbac#20]
I'm getting into several problems when using this package under Django 1.8:
- ImproperlyConfigured exception:

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/jeancventura/.virtualenvs/msw/lib/python3.4/site-packages/django/core/management/__init__.py", line 351, in execute_from_command_line
    utility.execute()
  File "/home/jeancventura/.virtualenvs/msw/lib/python3.4/site-packages/django/core/management/__init__.py", line 325, in execute
    django.setup()
  File "/home/jeancventura/.virtualenvs/msw/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/jeancventura/.virtualenvs/msw/lib/python3.4/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/home/jeancventura/.virtualenvs/msw/lib/python3.4/site-packages/django/contrib/admin/apps.py", line 22, in ready
    self.module.autodiscover()
  File "/home/jeancventura/.virtualenvs/msw/lib/python3.4/site-packages/django/contrib/admin/__init__.py", line 24, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/home/jeancventura/.virtualenvs/msw/lib/python3.4/site-packages/django/utils/module_loading.py", line 74, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/home/jeancventura/.virtualenvs/msw/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/jeancventura/.virtualenvs/msw/lib/python3.4/site-packages/django_prbac/admin.py", line 23, in <module>
    class RoleAdminForm(forms.ModelForm):
  File "/home/jeancventura/.virtualenvs/msw/lib/python3.4/site-packages/django/forms/models.py", line 274, in __new__
    "needs updating." % name
django.core.exceptions.ImproperlyConfigured: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is prohibited; form RoleAdminForm needs updating.
```

I'm was able to fix this by placing `fields = '__all__'` under the RoleAdminForm Meta class.
- After that was fixed, I'm getting:

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/jeancventura/.virtualenvs/msw/lib/python3.4/site-packages/django/core/management/__init__.py", line 351, in execute_from_command_line
    utility.execute()
  File "/home/jeancventura/.virtualenvs/msw/lib/python3.4/site-packages/django/core/management/__init__.py", line 325, in execute
    django.setup()
  File "/home/jeancventura/.virtualenvs/msw/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/jeancventura/.virtualenvs/msw/lib/python3.4/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/home/jeancventura/.virtualenvs/msw/lib/python3.4/site-packages/django/contrib/admin/apps.py", line 22, in ready
    self.module.autodiscover()
  File "/home/jeancventura/.virtualenvs/msw/lib/python3.4/site-packages/django/contrib/admin/__init__.py", line 24, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/home/jeancventura/.virtualenvs/msw/lib/python3.4/site-packages/django/utils/module_loading.py", line 74, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/home/jeancventura/.virtualenvs/msw/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/jeancventura/.virtualenvs/msw/lib/python3.4/site-packages/django_prbac/admin.py", line 23, in <module>
    class RoleAdminForm(forms.ModelForm):
  File "/home/jeancventura/.virtualenvs/msw/lib/python3.4/site-packages/django/forms/models.py", line 285, in __new__
    opts.help_texts, opts.error_messages)
  File "/home/jeancventura/.virtualenvs/msw/lib/python3.4/site-packages/django/forms/models.py", line 212, in fields_for_model
    formfield = f.formfield(**kwargs)
  File "/home/jeancventura/.virtualenvs/msw/lib/python3.4/site-packages/django_prbac/fields.py", line 74, in formfield
    return super(StringListField, self).formfield(**defaults)
  File "/home/jeancventura/.virtualenvs/msw/lib/python3.4/site-packages/django/db/models/fields/__init__.py", line 2169, in formfield
    return super(TextField, self).formfield(**defaults)
  File "/home/jeancventura/.virtualenvs/msw/lib/python3.4/site-packages/django/db/models/fields/__init__.py", line 912, in formfield
    return form_class(**defaults)
  File "/home/jeancventura/.virtualenvs/msw/lib/python3.4/site-packages/django_prbac/forms.py", line 47, in __init__
    super(StringListFormField, self).__init__(*args, **defaults)
TypeError: __init__() got an unexpected keyword argument 'max_length'
```

I was able to get around this problem by modifying StringLstFormField.**init** to not consider 'max_length' before calling super (`kwargs.pop('max_length')`). This doesn't seem like the right way to do this and would appreciate any suggestions as to how can I approach this.
- Other than that, I'm getting Django 1.9 deprecation warnings:

```
/home/jeancventura/.virtualenvs/msw/lib/python3.4/importlib/_bootstrap.py:321: RemovedInDjango19Warning: The django.forms.util module has been renamed. Use django.forms.utils instead.
  return f(*args, **kwds)

/home/jeancventura/.virtualenvs/msw/lib/python3.4/importlib/_bootstrap.py:321: RemovedInDjango19Warning: django.contrib.contenttypes.generic is deprecated and will be removed in Django 1.9. Its contents have been moved to the fields, forms, and admin submodules of django.contrib.contenttypes.
  return f(*args, **kwds)

/home/jeancventura/.virtualenvs/msw/lib/python3.4/importlib/_bootstrap.py:321: RemovedInDjango19Warning: The django.forms.util module has been renamed. Use django.forms.utils instead.
  return f(*args, **kwds)

/home/jeancventura/.virtualenvs/msw/lib/python3.4/importlib/_bootstrap.py:321: RemovedInDjango19Warning: django.contrib.contenttypes.generic is deprecated and will be removed in Django 1.9. Its contents have been moved to the fields, forms, and admin submodules of django.contrib.contenttypes.
  return f(*args, **kwds)
```

No idea yet about this warnings.

I want to submit a pull request with this fixes, but I'll wait until I have all issues properly fixed.

**Comment by czue** [comment]
thanks for the feedback - we're currently running `1.7` so not on our immediate radar to resolve these at the moment, but would definitely appreciate a PR to support the upgrade!

**Comment by GertBurger** [comment]
Hi

We did a 1.8 upgrade on prbac a while back but have not PR'd it yet.

https://github.com/GertBurger/django-prbac/commits/feature-add-django-1.8-support

**Comment by nickpell** [comment]
With https://github.com/dimagi/django-prbac/pull/30 we now support django 1.8 through 1.10.
